clear;
close all
load results_2055
figure;
vs_titles = ["locFree", "locBased", ...
    "locFreeH", "locBasedH", "hybrid", "true"];
str_dataset.animator.storyBoard([...
    str_mapEstimates.locFree'...
    str_mapEstimates.locBased' ...
    str_mapEstimates.locFree_fromHybrid' ...
    str_mapEstimates.locBased_fromHybrid' ...
    str_mapEstimates.hybrid(:) ...
    trueGains(:)], ...
    vec(vs_titles), 3:3:9);