clear
gsinfo;
load savedResults/results_2515.mat
vs_titles = ["locF", "locB", ...
"MoE.locF", "MoE.locB", "MoE", "true"];

figure;
str_dataset.animator.storyBoard([...
str_mapEstimates.locFree'...
str_mapEstimates.locBased' ...
str_mapEstimates.locFree_fromHybrid' ...
str_mapEstimates.locBased_fromHybrid' ...
str_mapEstimates.hybrid(:) ...
trueGains(:)], ...
vec(vs_titles), 3:3:9);

